### PR TITLE
Fix devcontainer config to use new vscode user

### PR DESCRIPTION
**Pull request by dbarrous**
This PR (will be very similar to the other 4), it helps address this issue: https://github.com/HERMES-SOC/hermes_eea/issues/6

It sets the default user of the devcontainer to be the new `vscode` user that is introduced in this PR (Should be merged after this one is merged): https://github.com/HERMES-SOC/sdc_aws_base_docker_image/pull/23

It also fixes a few path issues that were pointed out in the issue.

### CODE REVIEW

**Review by ehsteve — APPROVED** [review]

**Comment by liamgreenlee** [comment]
I'm having a few problems with the updates you have here:
1. The default shell is `/bin/sh` not `/bin/bash`
2. Git does not work by default. `git config --global --add safe.directory /workspaces/hermes_eea` is required first.
3. Write permissions do not work on linux because the remote user does not inherit the uid/guid from the local user

**Comment by ehsteve** [comment]
@dbarrous see comment above. Also, is this also changed in hermes_instrument which would mean that cruft will open a PR automatically to make these same changes, right?

**Comment by ehsteve** [comment]
Also this change should be done through the `hermes_instrument` template.

**Review by ehsteve — APPROVED** [review]

**Review by ehsteve — APPROVED** [review]

**Comment by dbarrous** [comment]
@liamgreenlee Hi Liam, apologies for the late response. I've been able to fix the issue for the default terminal to be bash instead of sh. However, it will be addressed in a new PR since this one will be closed in favor of our new across-repo way of making changes to templates. On the issue with git the way we've been utilizing the `.devcontainer` is only running testing out the application/any changes to the application. When we submit changes to git we either exit out of the container and then commit our changes either through the terminal or GitHub Desktop. I'll edit this response with the linked issues in a few.

**Pull request closed without merging**
