### PR TITLE
EEA Instrument code to produce L1A file.

### PR DESCRIPTION
**Pull request by rstrub**
EEA Instrument Merge Request. The process of putting CCSDS packets into L1A CDF was already quite familiar to me  but the github, python, vscode stuff made it much more uncertain...I wouldn't say difficult... At first it was uncertain because of the whole VScode devcontainer business. I didn't know at first I could easily ignore that stuff and use my own Pycharm IDE. Also, the function names provided in test_calibration.py and calibration.py and some python syntax that was new to me. Near the end it was filled with uncertainty because of much of the github workflow procedures were quite new to me.  It is still difficult because I am not even sure if this is the PR description I am supposed to update or not and  docstrings are also new to me.  The CDFLIB issue was a big sticking point...Over the years I have moved from C->Perl->C++->Python->Javascript->Java->IDL->Python.  I think many of my colleagues perhaps have had similar travels.  So all these python-centric concepts were troublesome. But I certainly appreciate the role they all play.

### CODE REVIEW

**Comment by ehsteve** [comment]
@rstrub sorry this is taking so long on our end. We were all at AGU. @dbarrous needs to do some refactoring to be able to add a pipeline test to GitHub so that is being worked on. In the meantime we'll provide some feedback on some other aspects of the code next week. Does that work for you?

**Comment by rstrub** [comment]
> @rstrub sorry this is taking so long on our end. We were all at AGU. @dbarrous needs to do some refactoring to be able to add a pipeline test to GitHub so that is being worked on. In the meantime we'll provide some feedback on some other aspects of the code next week. Does that work for you?

Yes, I was assuming that this was going to take a few office hours and perahaps a couple one on one meetings,

**Comment by dbarrous** [comment]
> > @rstrub sorry this is taking so long on our end. We were all at AGU. @dbarrous needs to do some refactoring to be able to add a pipeline test to GitHub so that is being worked on. In the meantime we'll provide some feedback on some other aspects of the code next week. Does that work for you?
> 
> Yes, I was assuming that this was going to take a few office hours and perahaps a couple one on one meetings,

I should have a PR with the refactoring done in a few days, we had extracted some of the logic to a different artifact lambda function to keep the processing lambda lean and be able to run within a Git workflow. The goal is to have a new CI/CD workflow/test which takes whatever code you have for calibrating your files to L1 and tries to generate a L1 CDF product from it and give you a download link so you can verify. Hopefully, we can meet up sometime next week to test out your merge request ^

**Comment by rstrub** [comment]
go_plotly is a graphic diff for real warm fuzzies

**Review by swkre — APPROVED** [review]

**Review by dbarrous — CHANGES_REQUESTED** [review]
This PR looks good, reviewed by @Alrobbertz and I. We will approve it once the docstrings are reformatted or added to the newly added functions and classes. Also would greatly appreciate changing the title to something a bit more informative, and adding a bit more to the description of the Pull Request with what has been added and maybe your thoughts and tips of the process so we can use this Pull Request as an example for other instrument teams. Thanks so much again @rstrub! :)

**Comment by dbarrous** [comment]
Corrected the linting issues and resolved the failed Windows tests. I adjusted the `test_process_file` function to include a retry mechanism for handling Windows PermissionError. Due to Windows' strict file locking compared to Mac and Linux, files can be locked longer than expected, leading to exceptions. The issue was Python tried to remove files from a temporary directory while they were still in use by a process.

After these fixes this PR looks good to me and has my approval, any thoughts @ehsteve or @Alrobbertz before squashing and merging?

**Review by dbarrous — APPROVED** [review]

**Pull request merged**
